// utils/constants.js
module.exports = {
  EVENTS: {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILED: "REGISTER_FAILED",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOGOUT: "LOGOUT",
    EMAIL_SENT: "EMAIL_SENT",
    PASSWORD_RESET_REQUEST: "PASSWORD_RESET_REQUEST",
    PASSWORD_RESET_SUCCESS: "PASSWORD_RESET_SUCCESS",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED",
    ERROR: "ERROR", // Generic server error
  }
};